---
repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0
    hooks:
    -   id: clang-format

- repo: https://github.com/codespell-project/codespell
  # Configuration for codespell is in .pre-commit-config.yaml
  rev: v2.4.1
  hooks:
  - id: codespell
